var convert = new Map([
  ["ZWE", "Zimbabwe"],
  ["ZMB", "Zambia"],
  ["YEM", "Yemen"],
  ["VNM", "Viet Nam"],
  ["VEN", "Venezuela (Bolivarian Republic of)"],
  ["VUT", "Vanuatu"],
  ["UZB", "Uzbekistan"],
  ["URY", "Uruguay"],
  ["FSM", "Micronesia (Federated States of)"],
  ["MHL", "Marshall Islands"],
  ["MNP", "Northern Mariana Islands"],
  ["VIR", "United States Virgin Islands"],
  ["GUM", "Guam"],
  ["ASM", "American Samoa"],
  ["PRI", "Puerto Rico"],
  ["USA", "United States of America"],
  ["SGS", "South Georgia and the South Sandwich Islands"],
  ["IOT", "British Indian Ocean Territory"],
  ["SHN", "Saint Helena"],
  ["PCN", "Pitcairn"],
  ["AIA", "Anguilla"],
  ["FLK", "Falkland Islands (Malvinas)"],
  ["CYM", "Cayman Islands"],
  ["BMU", "Bermuda"],
  ["VGB", "British Virgin Islands"],
  ["TCA", "Turks and Caicos Islands"],
  ["MSR", "Montserrat"],
  ["JEY", "Jersey"],
  ["GGY", "Guernsey"],
  ["IMN", "Isle of Man"],
  ["GBR", "United Kingdom of Great Britain and Northern Ireland"],
  ["ARE", "United Arab Emirates"],
  ["UKR", "Ukraine"],
  ["UGA", "Uganda"],
  ["TKM", "Turkmenistan"],
  ["TUR", "Turkey"],
  ["TUN", "Tunisia"],
  ["TTO", "Trinidad and Tobago"],
  ["TON", "Tonga"],
  ["TGO", "Togo"],
  ["TLS", "Timor-Leste"],
  ["THA", "Thailand"],
  ["TZA", "United Republic of Tanzania"],
  ["TJK", "Tajikistan"],
  ["SYR", "Syrian Arab Republic"],
  ["CHE", "Switzerland"],
  ["SWE", "Sweden"],
  ["SWZ", "Swaziland"],
  ["SUR", "Suriname"],
  ["SSD", "South Sudan"],
  ["SDN", "Sudan"],
  ["LKA", "Sri Lanka"],
  ["ESP", "Spain"],
  ["KOR", "Republic of Korea"],
  ["ZAF", "South Africa"],
  ["SOM", "Somalia"],
  ["SLB", "Solomon Islands"],
  ["SVK", "Slovakia"],
  ["SVN", "Slovenia"],
  ["SGP", "Singapore"],
  ["SLE", "Sierra Leone"],
  ["SYC", "Seychelles"],
  ["SRB", "Serbia"],
  ["SEN", "Senegal"],
  ["SAU", "Saudi Arabia"],
  ["STP", "Sao Tome and Principe"],
  ["SMR", "San Marino"],
  ["WSM", "Samoa"],
  ["VCT", "Saint Vincent and the Grenadines"],
  ["LCA", "Saint Lucia"],
  ["KNA", "Saint Kitts and Nevis"],
  ["RWA", "Rwanda"],
  ["RUS", "Russian Federation"],
  ["ROU", "Romania"],
  ["QAT", "Qatar"],
  ["PRT", "Portugal"],
  ["POL", "Poland"],
  ["PHL", "Philippines"],
  ["PER", "Peru"],
  ["PRY", "Paraguay"],
  ["PNG", "Papua New Guinea"],
  ["PAN", "Panama"],
  ["PLW", "Palau"],
  ["PAK", "Pakistan"],
  ["OMN", "Oman"],
  ["NOR", "Norway"],
  ["PRK", "Democratic People's Republic of Korea"],
  ["NGA", "Nigeria"],
  ["NER", "Niger"],
  ["NIC", "Nicaragua"],
  ["NZL", "New Zealand"],
  ["NIU", "Niue"],
  ["COK", "Cook Islands"],
  ["NLD", "Netherlands"],
  ["ABW", "Aruba"],
  ["CUW", "Curaçao"],
  ["NPL", "Nepal"],
  ["NRU", "Nauru"],
  ["NAM", "Namibia"],
  ["MOZ", "Mozambique"],
  ["MAR", "Morocco"],
  ["ESH", "Western Sahara"],
  ["MNE", "Montenegro"],
  ["MNG", "Mongolia"],
  ["MDA", "Republic of Moldova"],
  ["MCO", "Monaco"],
  ["MEX", "Mexico"],
  ["MUS", "Mauritius"],
  ["MRT", "Mauritania"],
  ["MLT", "Malta"],
  ["MLI", "Mali"],
  ["MDV", "Maldives"],
  ["MYS", "Malaysia"],
  ["MWI", "Malawi"],
  ["MDG", "Madagascar"],
  ["MKD", "The former Yugoslav Republic of Macedonia"],
  ["LUX", "Luxembourg"],
  ["LTU", "Lithuania"],
  ["LIE", "Liechtenstein"],
  ["LBY", "Libya"],
  ["LBR", "Liberia"],
  ["LSO", "Lesotho"],
  ["LBN", "Lebanon"],
  ["LVA", "Latvia"],
  ["LAO", "Lao People's Democratic Republic"],
  ["KGZ", "Kyrgyzstan"],
  ["KWT", "Kuwait"],
  ["KIR", "Kiribati"],
  ["KEN", "Kenya"],
  ["KAZ", "Kazakhstan"],
  ["JOR", "Jordan"],
  ["JPN", "Japan"],
  ["JAM", "Jamaica"],
  ["ITA", "Italy"],
  ["ISR", "Israel"],
  ["PSE", "State of Palestine"],
  ["IRL", "Ireland"],
  ["IRQ", "Iraq"],
  ["IRN", "Iran (Islamic Republic of)"],
  ["IDN", "Indonesia"],
  ["IND", "India"],
  ["ISL", "Iceland"],
  ["HUN", "Hungary"],
  ["HND", "Honduras"],
  ["HTI", "Haiti"],
  ["GUY", "Guyana"],
  ["GNB", "Guinea-Bissau"],
  ["GIN", "Guinea"],
  ["GTM", "Guatemala"],
  ["GRD", "Grenada"],
  ["GRC", "Greece"],
  ["GHA", "Ghana"],
  ["DEU", "Germany"],
  ["GEO", "Georgia"],
  ["GMB", "Gambia"],
  ["GAB", "Gabon"],
  ["FRA", "France"],
  ["SPM", "Saint Pierre and Miquelon"],
  ["WLF", "Wallis and Futuna Islands"],
  ["MAF", "Saint Martin (French Part)"],
  ["BLM", "Saint Barthélemy"],
  ["PYF", "French Polynesia"],
  ["NCL", "New Caledonia"],
  ["ALA", "Åland Islands"],
  ["FIN", "Finland"],
  ["FJI", "Fiji"],
  ["ETH", "Ethiopia"],
  ["EST", "Estonia"],
  ["ERI", "Eritrea"],
  ["GNQ", "Equatorial Guinea"],
  ["SLV", "El Salvador"],
  ["EGY", "Egypt"],
  ["ECU", "Ecuador"],
  ["DOM", "Dominican Republic"],
  ["DMA", "Dominica"],
  ["DJI", "Djibouti"],
  ["GRL", "Greenland"],
  ["FRO", "Faroe Islands"],
  ["DNK", "Denmark"],
  ["CZE", "Czechia"],
  ["CYP", "Cyprus"],
  ["CUB", "Cuba"],
  ["HRV", "Croatia"],
  ["CIV", "Côte d'Ivoire"],
  ["CRI", "Costa Rica"],
  ["COD", "Democratic Republic of the Congo"],
  ["COG", "Congo"],
  ["COM", "Comoros"],
  ["COL", "Colombia"],
  ["CHN", "China"],
  ["MAC", "China, Macao Special Administrative Region"],
  ["HKG", "China, Hong Kong Special Administrative Region"],
  ["CHL", "Chile"],
  ["TCD", "Chad"],
  ["CAF", "Central African Republic"],
  ["CPV", "Cabo Verde"],
  ["CAN", "Canada"],
  ["CMR", "Cameroon"],
  ["KHM", "Cambodia"],
  ["MMR", "Myanmar"],
  ["BDI", "Burundi"],
  ["BFA", "Burkina Faso"],
  ["BGR", "Bulgaria"],
  ["BRN", "Brunei Darussalam"],
  ["BRA", "Brazil"],
  ["BWA", "Botswana"],
  ["BIH", "Bosnia and Herzegovina"],
  ["BOL", "Bolivia (Plurinational State of)"],
  ["BTN", "Bhutan"],
  ["BEN", "Benin"],
  ["BLZ", "Belize"],
  ["BEL", "Belgium"],
  ["BLR", "Belarus"],
  ["BRB", "Barbados"],
  ["BGD", "Bangladesh"],
  ["BHR", "Bahrain"],
  ["BHS", "Bahamas"],
  ["AZE", "Azerbaijan"],
  ["AUT", "Austria"],
  ["AUS", "Australia"],
  ["HMD", "Heard Island and McDonald Islands"],
  ["NFK", "Norfolk Island"],
  ["ARM", "Armenia"],
  ["ARG", "Argentina"],
  ["ATG", "Antigua and Barbuda"],
  ["AGO", "Angola"],
  ["AND", "Andorra"],
  ["DZA", "Algeria"],
  ["ALB", "Albania"],
  ["AFG", "Afghanistan"],
  ["ATA", "Antarctica"],
  ["SXM", "Sint Maarten (Dutch part)"]
])

function convertCountries(data) {
  for (var i=0; i < data.length; i++) {
    var iso = data[i].country_iso;
    // if found in convert...
    if (convert.get(iso) !== undefined) {
      data[i].country_iso = convert.get(iso)
    }
  }
  return data;
}

/*
function convertISO(data, csv_data) {
  var convertString = '';
  console.log(convert.length)
  for (var i=0; i < convert.length; i++) {
    for (var j=0; j < csv_data.length; j++) {
      var en1 = csv_data[j]["official_name_en"];
      var en2 = csv_data[j]["official_name_en"];
      //console.log(en)
      console.log(convert[i][0]);
      if (convert[i][0] === en1) {
        console.log("FOUND IT " + en1)
        var iso = csv_data[j]["ISO3166-1-Alpha-3"];
        convertString += '["'+iso+'", "'+en2+'"],\n'
      }
    }
  }
  console.log(convertString);
  return data;
}
*/
