var convert = new Map([
// all possible countries to convert
//  ["Zimbabwe", "Zimbabwe"],
//  ["Zambia", "Zambia"],
//  ["Yemen", "Yemen"],
  ["Viet Nam", "Vietnam"],
  ["Venezuela (Bolivarian Republic of)", "Venezuela"],
//  ["Vanuatu", "Vanuatu"],
//  ["Uzbekistan", "Uzbekistan"],
//  ["Uruguay", "Uruguay"],
  ["Micronesia (Federated States of)", "Micronesia"],
  ["Marshall Islands", "Marshall Is."],
  ["Northern Mariana Islands", "N. Mariana Is."],
  ["United States Virgin Islands", "U.S. Virgin Is."],
//  ["Guam", "Guam"],
//  ["American Samoa", "American Samoa"],
//  ["Puerto Rico", "Puerto Rico"],
//  ["United States of America", "United States of America"],
  ["South Georgia and the South Sandwich Islands", "S. Geo. and the Is."],
  ["British Indian Ocean Territory", "Br. Indian Ocean Ter."],
//  ["Saint Helena", "Saint Helena"],
  ["Pitcairn", "Pitcairn Is."],
//  ["Anguilla", "Anguilla"],
  ["Falkland Islands (Malvinas)", "Falkland Is."],
  ["Cayman Islands", "Cayman Is."],
//  ["Bermuda", "Bermuda"],
  ["British Virgin Islands", "British Virgin Is."],
  ["Turks and Caicos Islands", "Turks and Caicos Is."],
//  ["Montserrat", "Montserrat"],
//  ["Jersey", "Jersey"],
//  ["Guernsey", "Guernsey"],
//  ["Isle of Man", "Isle of Man"],
  ["United Kingdom of Great Britain and Northern Ireland", "United Kingdom"],
//  ["United Arab Emirates", "United Arab Emirates"],
//  ["Ukraine", "Ukraine"],
//  ["Uganda", "Uganda"],
//  ["Turkmenistan", "Turkmenistan"],
//  ["Turkey", "Turkey"],
//  ["Tunisia", "Tunisia"],
//  ["Trinidad and Tobago", "Trinidad and Tobago"],
//  ["Tonga", "Tonga"],
//  ["Togo", "Togo"],
//  ["Timor-Leste", "Timor-Leste"],
//  ["Thailand", "Thailand"],
  ["United Republic of Tanzania", "Tanzania"],
//  ["Tajikistan", "Tajikistan"],
  ["Syrian Arab Republic", "Syria"],
//  ["Switzerland", "Switzerland"],
//  ["Sweden", "Sweden"],
  ["Swaziland", "eSwatini"],
//  ["Suriname", "Suriname"],
  ["South Sudan", "S. Sudan"],
//  ["Sudan", "Sudan"],
//  ["Sri Lanka", "Sri Lanka"],
//  ["Spain", "Spain"],
  ["Republic of Korea", "South Korea"],
//  ["South Africa", "South Africa"],
//  ["Somalia", "Somalia"],
  ["Solomon Islands", "Solomon Is."],
//  ["Slovakia", "Slovakia"],
//  ["Slovenia", "Slovenia"],
//  ["Singapore", "Singapore"],
//  ["Sierra Leone", "Sierra Leone"],
//  ["Seychelles", "Seychelles"],
//  ["Serbia", "Serbia"],
//  ["Senegal", "Senegal"],
//  ["Saudi Arabia", "Saudi Arabia"],
  ["Sao Tome and Principe", "São Tomé and Principe"],
//  ["San Marino", "San Marino"],
//  ["Samoa", "Samoa"],
  ["Saint Vincent and the Grenadines", "St. Vin. and Gren."],
//  ["Saint Lucia", "Saint Lucia"],
  ["Saint Kitts and Nevis", "St. Kitts and Nevis"],
//  ["Rwanda", "Rwanda"],
  ["Russian Federation", "Russia"],
//  ["Romania", "Romania"],
//  ["Qatar", "Qatar"],
//  ["Portugal", "Portugal"],
//  ["Poland", "Poland"],
//  ["Philippines", "Philippines"],
//  ["Peru", "Peru"],
//  ["Paraguay", "Paraguay"],
//  ["Papua New Guinea", "Papua New Guinea"],
//  ["Panama", "Panama"],
//  ["Palau", "Palau"],
//  ["Pakistan", "Pakistan"],
//  ["Oman", "Oman"],
//  ["Norway", "Norway"],
  ["Democratic People's Republic of Korea", "North Korea"],
//  ["Nigeria", "Nigeria"],
//  ["Niger", "Niger"],
//  ["Nicaragua", "Nicaragua"],
//  ["New Zealand", "New Zealand"],
//  ["Niue", "Niue"],
  ["Cook Islands", "Cook Is."],
//  ["Netherlands", "Netherlands"],
//  ["Aruba", "Aruba"],
//  ["Curaçao", "Curaçao"],
//  ["Nepal", "Nepal"],
//  ["Nauru", "Nauru"],
//  ["Namibia", "Namibia"],
//  ["Mozambique", "Mozambique"],
//  ["Morocco", "Morocco"],
  ["Western Sahara", "W. Sahara"],
//  ["Montenegro", "Montenegro"],
//  ["Mongolia", "Mongolia"],
  ["Republic of Moldova", "Moldova"],
//  ["Monaco", "Monaco"],
//  ["Mexico", "Mexico"],
//  ["Mauritius", "Mauritius"],
//  ["Mauritania", "Mauritania"],
//  ["Malta", "Malta"],
//  ["Mali", "Mali"],
//  ["Maldives", "Maldives"],
//  ["Malaysia", "Malaysia"],
//  ["Malawi", "Malawi"],
//  ["Madagascar", "Madagascar"],
  ["The former Yugoslav Republic of Macedonia", "Macedonia"],
//  ["Luxembourg", "Luxembourg"],
//  ["Lithuania", "Lithuania"],
//  ["Liechtenstein", "Liechtenstein"],
//  ["Libya", "Libya"],
//  ["Liberia", "Liberia"],
//  ["Lesotho", "Lesotho"],
//  ["Lebanon", "Lebanon"],
//  ["Latvia", "Latvia"],
  ["Lao People's Democratic Republic", "Laos"],
//  ["Kyrgyzstan", "Kyrgyzstan"],
//  ["Kuwait", "Kuwait"],
//  ["Kiribati", "Kiribati"],
//  ["Kenya", "Kenya"],
//  ["Kazakhstan", "Kazakhstan"],
//  ["Jordan", "Jordan"],
//  ["Japan", "Japan"],
//  ["Jamaica", "Jamaica"],
//  ["Italy", "Italy"],
//  ["Israel", "Israel"],
  ["State of Palestine", "Palestine"],
//  ["Ireland", "Ireland"],
//  ["Iraq", "Iraq"],
  ["Iran (Islamic Republic of)", "Iran"],
//  ["Indonesia", "Indonesia"],
//  ["India", "India"],
//  ["Iceland", "Iceland"],
//  ["Hungary", "Hungary"],
//  ["Honduras", "Honduras"],
//  ["Haiti", "Haiti"],
//  ["Guyana", "Guyana"],
//  ["Guinea-Bissau", "Guinea-Bissau"],
//  ["Guinea", "Guinea"],
//  ["Guatemala", "Guatemala"],
//  ["Grenada", "Grenada"],
//  ["Greece", "Greece"],
//  ["Ghana", "Ghana"],
//  ["Germany", "Germany"],
//  ["Georgia", "Georgia"],
//  ["Gambia", "Gambia"],
//  ["Gabon", "Gabon"],
//  ["France", "France"],
  ["Saint Pierre and Miquelon", "St. Pierre and Miquelon"],
  ["Wallis and Futuna Islands", "Wallis and Futuna Is."],
  ["Saint Martin (French Part)", "St-Martin"],
  ["Saint Barthélemy", "St-Barthélemy"],
  ["French Polynesia", "Fr. Polynesia"],
//  ["New Caledonia", "New Caledonia"],
  ["Åland Islands", "Åland"],
//  ["Finland", "Finland"],
//  ["Fiji", "Fiji"],
//  ["Ethiopia", "Ethiopia"],
//  ["Estonia", "Estonia"],
//  ["Eritrea", "Eritrea"],
  ["Equatorial Guinea", "Eq. Guinea"],
//  ["El Salvador", "El Salvador"],
//  ["Egypt", "Egypt"],
//  ["Ecuador", "Ecuador"],
  ["Dominican Republic", "Dominican Rep."],
//  ["Dominica", "Dominica"],
//  ["Djibouti", "Djibouti"],
//  ["Greenland", "Greenland"],
  ["Faroe Islands", "Faeroe Is."],
//  ["Denmark", "Denmark"],
//  ["Czechia", "Czechia"],
//  ["Cyprus", "Cyprus"],
//  ["Cuba", "Cuba"],
//  ["Croatia", "Croatia"],
//  ["Côte d'Ivoire", "Côte d'Ivoire"],
//  ["Costa Rica", "Costa Rica"],
  ["Democratic Republic of the Congo", "Dem. Rep. Congo"],
//  ["Congo", "Congo"],
//  ["Comoros", "Comoros"],
//  ["Colombia", "Colombia"],
//  ["China", "China"],
  ["China, Macao Special Administrative Region", "Macao"],
  ["China, Hong Kong Special Administrative Region", "Hong Kong"],
//  ["Chile", "Chile"],
//  ["Chad", "Chad"],
  ["Central African Republic", "Central African Rep."],
//  ["Cabo Verde", "Cabo Verde"],
//  ["Canada", "Canada"],
//  ["Cameroon", "Cameroon"],
//  ["Cambodia", "Cambodia"],
//  ["Myanmar", "Myanmar"],
//  ["Burundi", "Burundi"],
//  ["Burkina Faso", "Burkina Faso"],
//  ["Bulgaria", "Bulgaria"],
  ["Brunei Darussalam", "Brunei"],
//  ["Brazil", "Brazil"],
//  ["Botswana", "Botswana"],
  ["Bosnia and Herzegovina", "Bosnia and Herz."],
  ["Bolivia (Plurinational State of)", "Bolivia"],
//  ["Bhutan", "Bhutan"],
//  ["Benin", "Benin"],
//  ["Belize", "Belize"],
//  ["Belgium", "Belgium"],
//  ["Belarus", "Belarus"],
//  ["Barbados", "Barbados"],
//  ["Bangladesh", "Bangladesh"],
//  ["Bahrain", "Bahrain"],
//  ["Bahamas", "Bahamas"],
//  ["Azerbaijan", "Azerbaijan"],
//  ["Austria", "Austria"],
//  ["Australia", "Australia"],
  ["Heard Island and McDonald Islands", "Heard I. and McDonald Is."],
  ["Norfolk Island", "Norfolk Island"],
//  ["Armenia", "Armenia"],
//  ["Argentina", "Argentina"],
  ["Antigua and Barbuda", "Antigua and Barb."],
//  ["Angola", "Angola"],
//  ["Andorra", "Andorra"],
//  ["Algeria", "Algeria"],
//  ["Albania", "Albania"],
//  ["Afghanistan", "Afghanistan"],
//  ["Antarctica", "Antarctica"],
  ["Sint Maarten (Dutch part)", "Sint Maarten"]
])

/*
  ["", "Somaliland"],
  ["", "Siachen Glacier"],
  ["", "Indian Ocean Ter."],
  ["", "Ashmore and Cartier Is."],
  ["", "N. Cyprus"],
  ["", "Fr. S. Antarctic Lands"],
  ["", "Kosovo"],
  ["", "Taiwan"],
  ["", "Vatican"],
  Bonaire, Sint Eustatius and Saba
  Bouvet Island
  Christmas Island
  Cocos (Keeling) Islands
  French Guiana
  French Southern Territories
  Gibraltar
  Guadeloupe
  Holy See
  Martinique
  Mayotte
  Réunion
  Sark
  Svalbard and Jan Mayen Islands
  Tokelau
  Tuvalu
  United States Minor Outlying Islands
*/

function convertCountries(data) {
  for (var i=0; i < data.length; i++) {
    // if found in convert...
    if (convert.get(data[i]) !== undefined) {
      data[i] = convert.get(data[i])
    }
  }
  return data;
}
